export default {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  CHANGE_AVATAR_REQUEST: "USERS_CHANGE_AVATAR_REQUEST",
  CHANGE_AVATAR_SUCCCESS: "USERS_CHANGE_AVATAR_SUCCCESS",
  CHANGE_AVATAR_FAILURE: "USERS_CHANGE_AVATAR_FAILURE",

  LOGOUT: "USERS_LOGOUT"
};
